[workspace]
resolver = "2"
members = [

    "generator",
    "server",
    "core",
]
exclude = ["submodules/llama-rust","submodules/llama2.rs",
]

[profile.release]
debug = true

[profile.smol]
inherits = "release"
strip = true